backend:
  name: git-gateway

media_folder: "site/static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "home"
    label: "Home"
    files:
      - file: "site/content/_index.pt.md"
        label: "Home Page PT"
        name: "homePT"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string, required: false},
              {label: "Text", name: "text", widget: "text", required: false}]}
          - label: Services
            name: services
            widget: object
            required: false
            fields:
              - label: Linhas
                name: rows
                widget: list
                required: false
                fields:
                  - label: Serviços
                    name: items
                    widget: list
                    required: false
                    fields: 
                      - label: Serviço
                        name: heading
                        widget: text
                        required: false
                      - label: Imagem
                        name: image
                        widget: image
                        required: false
                      - label: Slideshow
                        name: carouselslides
                        widget: list
                        required: false
                        fields: 
                          - label: Imagem
                            name: image
                            widget: image
                            required: false
                      - label: Conteúdo
                        name: content
                        widget: text
                        required: false
                      - label: Conteúdo Grelha
                        name: intro
                        widget: object
                        required: false
                        fields:
                          - label: Conteúdo
                            name: blurbs
                            widget: list
                            required: false
                            fields:
                              - label: Descrição
                                name: text
                                widget: text
                                required: false
                              - label: Imagem
                                name: image
                                widget: image
                                required: false
                      - label: SubServiço
                        name: availableOffices
                        widget: list
                        required: false
                        fields: 
                          - label: SubServiço
                            name: title
                            widget: text
                            required: false
                          - label: Slideshow
                            name: carouselslides
                            widget: list
                            required: false
                            fields: 
                              - label: Imagem
                                name: image
                                widget: image
                                required: false
                          - label: Conteúdo
                            name: content
                            widget: text
                            required: false
                          - label: Conteúdo Grelha
                            name: intro
                            widget: object
                            required: false
                            fields:
                              - label: Conteúdo
                                name: blurbs
                                widget: list
                                required: false
                                fields:
                                  - label: Descrição
                                    name: text
                                    widget: text
                                    required: false
                                  - label: Imagem
                                    name: image
                                    widget: image
                                    required: false
                      - label: PDF
                        name: pdf
                        widget: object
                        required: false
                        fields:
                          - label: ID
                            name: idPdf
                            widget: string
                            required: false
  - name: "companies"
    label: "Companies"
    files:
      - file: "site/content/companies/_index.pt.md"
        label: "Companies Page PT"
        name: "companies"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - label: Values
            name: values
            widget: list
            required: false
            fields:
              - {label: Title, name: heading, widget: string, required: false}
              - {label: Website, name: web, widget: string, required: false}
              - {label: Email, name: email, widget: string, required: false}
              - {label: Text, name: text, widget: text, required: false}
              - {label: Image, name: imageUrl, widget: image, required: false}
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "site/content/news/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Intro Blurb", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "about"
    label: "About"
    files:
      - file: "site/content/about/_index.pt.md"
        label: "About Page PT"
        name: "AboutPT"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Body, name: body, widget: markdown, required: false}
          - {label: Slideshow, name: carouselslides, widget: list, required: false, fields: [
              {label: Image, name: image, widget: image, required: false
              }]}
  - name: "contact"
    label: "Contact"
    files:
      - file: "site/content/contact/_index.pt.md"
        label: "Contact Page PT"
        name: "contactPT"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - label: Contacts
            name: contacts
            widget: list
            required: false
            fields:
              - label: Heading
                name: text
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
              - label: UrlValue
                name: urlValue
                widget: string
                required: false
              - label: Value
                name: value
                widget: string
                required: false
          - label: Contact Entries
            name: contact_entries
            widget: list
            required: false
            fields:
              - label: Heading
                name: heading
                widget: string
                required: false
              - label: Text
                name: text
                widget: text
                required: false